### ISSUE TITLE
MajTod.http() missing 1 required positional argument: 'headers'

### ISSUE THREAD

**Issue by kiethopt** [akasakaid/majtod#2]
Selecting Multiple Process or Single Process is the same error, I hope you can fix it, thank you.

![image](https://github.com/user-attachments/assets/1d61431c-f002-45d7-bce4-819455e6b52e)

**Comment by akasakaid** [comment]
> Selecting Multiple Process or Single Process is the same error, I hope you can fix it, thank you.
> 
> ![image](https://github.com/user-attachments/assets/1d61431c-f002-45d7-bce4-819455e6b52e)
> 

Owhh yeah i forget add it, i will fix later.

**Comment by akasakaid** [comment]
Okay i already fix it, try to update it.
